name: short_assembly
channels:
  - conda-forge
  - bioconda
dependencies:
  - fastp=0.23.1
  - spades=3.15.3
  - minia=3.2.4
  - abyss=2.2.5
  - kmc=3.0.0
  - bwa=0.7.17
  - spades=3.15.3
  - quast=5.0.2
  - flash=1.2.11
  - busco=5.2.1
